name: Build

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          elixir-version: "1.18"
      - run: mix format --check-formatted
  test:
    name: Test on Elixir ${{ matrix.elixir }} (OTP ${{ matrix.otp }})
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        otp: ["26", "25"]
        elixir: ["1.18", "1.17", "1.16", "1.15", "1.14"]
        include:
          # Has issues that need to be resolved
          #- otp: "28"
          #  elixir: "1.18"
          - otp: "27"
            elixir: "1.18"
          - otp: "27"
            elixir: "1.17"
          - otp: "24"
            elixir: "1.15"
          - otp: "24"
            elixir: "1.14"
          # Elixir 1.14 still supports OTP 23, but it requires ubuntu-20.04
          # which is no longer supported in GH Actions
          # - otp: "23.3.4.20"
          #  elixir: "1.14.5"
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@v3
        name: Cache dependencies
        with:
          path: |
            deps
          key: deps-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-${{ hashFiles('mix.lock') }}
            deps-
      - run: mix deps.get
      - uses: actions/cache@v3
        name: Cache build
        with:
          path: |
            _build
          key: build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
            build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-
      - run: mix test
